apiVersion: v1
kind: Service
metadata:
  name: check-my-ip
spec:
  type: LoadBalancer
  selector:
    app: check-my-ip
  ports:
    - protocol: TCP
      port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}
