apiVersion: v1
entries:
  check-my-ip:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2025-09-16T12:35:55.559898392+06:00"
    description: A Helm chart for check pod ip
    digest: f13a85caad5623e7c389c76e653b53ea4570e9218dcadb364c4221280a15ac96
    name: check-my-ip
    type: application
    urls:
    - ./package/check-my-ip-1.0.1.tgz
    version: 1.0.1
  green-app:
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2025-09-16T12:35:55.565324367+06:00"
    description: A Helm chart for green  app
    digest: 981769c2dac1588a8755fbc015a2a8b1163de25c242c70ba397784db14aa03aa
    name: green-app
    type: application
    urls:
    - ./package/green-app-1.0.2.tgz
    version: 1.0.2
  red-app:
  - apiVersion: v2
    appVersion: 1.0.3
    created: "2025-09-16T12:35:55.570405405+06:00"
    description: A Helm chart for red  app
    digest: 9ad57e6ed0b509c36afe3c0e802cb476712541c1b207566dec75326e81daa79a
    name: red-app
    type: application
    urls:
    - ./package/red-app-1.0.3.tgz
    version: 1.0.3
generated: "2025-09-16T12:35:55.558316906+06:00"
